MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :bands do
    resources :albums do
      resources :tracks
    end
  end

  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create]

end

MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :name, :band_id, :recording_type, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Track
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album

  has_many :tracks,
    through: :albums,
    source: :tracks

end

MusicApp/app/models/track.rb
class Track < ApplicationRecord
  validates :album_id, :name, :track_type, :lyrics, presence: true

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Album
  
  has_one :band,
    through: :album,
    source: :band
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end


end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    @band = Band.find(params[:band_id])
  end

  def create
    @album = Album.new(album_params)
    @album.band_id = params[:band_id]
    if @album.save
      redirect_to "/bands/#{@album.band_id}/albums/#{@album.id}"
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to "/bands/#{@album.band_id}/albums/new"
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def show
    @album = Album.find_by(id: params[:id])
    @band = Band.find_by(id: @album.band_id)
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update_attributes(album_params)
      redirect_to band_album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_band_album_url
    end
  end

  def destroy
    album = Album.find_by(id: params[:id])
    album.destroy
    redirect_to band_url(params[:band_id])
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :recording_type)
  end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user.session_token == session[:session_token]
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_sessions_url
  end

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all.order(:name)
  end

  def show
    @band = Band.find_by(id: params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @bands.errors.full_messages
      redirect_to new_bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @bands.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render new_user_url
    end
  end

  def new; end

  def destroy
    log_out_user!
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def show
    @track = Track.find_by(id: params[:id])
    @album = Album.find_by(id: @track.album_id)
  end

  def update
  end

  def destroy
  end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    if @user
      render :show
    else
      flash[:errors] = ["You don't belong here!"]
      redirect_to new_sessions_url
    end
  end

  def new; end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    '<input type="hidden"
      name="authenticity_token"
      value="#{form_authencitity_token}">'.html_safe
  end

  def email_password
    '<label for="email">Email: </label>
    <input id="email" type="text" name="user[email]">
    <label for="password">Password</label>
    <input id="password" type="password" name="user[password]">'.html_safe
  end

end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/_form.html.erb
<% if action == :edit %>
  <% action_url = "/bands/#{album.band_id}/albums/#{album.id}" %>
<% else %>
  <% action_url = "/bands/#{band.id}/albums" %>
<% end %>

<form action=" <%= action_url %>" method="POST">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Title: </label>
  <input id="name" type="text" name="album[name]" value="<%=album.name%>">

  <br>
  <br>

  <label for="recording_type">Recording Type</label>
  <br>
  Live<input type="radio"
    name="album[recording_type]"
    value="studio"
    <%= album.recording_type == "studio" ? "checked" : "" %> >
  Studio<input type="radio" name="album[recording_type]" value="live"
  <%= album.recording_type == "live" ? "checked" : "" %> >

  <input type="submit" value= "Save" >
</form>

MusicApp/app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

MusicApp/app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

MusicApp/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render 'form', action: :edit, album: @album  %>

MusicApp/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', action: :new, album: @album, band: @band %>

MusicApp/app/views/albums/show.html.erb
<h1><%= link_to "#{@album.name}", "/bands/#{@band.id}" %></h1>

<br>
<br>
<% @album.tracks.try(:each) do |track| %>
  <%= link_to "#{track.name}", "/bands/#{@band.id}/albums/#{@album.id}/tracks/#{track.id}" %>

  <br><br>
<% end %>

<form action= "<%= band_album_url %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <%= auth_token %>

  <input type="submit" value="Delete album :(">
</form>

<form action= "<%= "/bands/#{@album.band_id}/albums/#{@album.id}/edit" %>" method="get">
  <%= auth_token %>

  <input type="submit" value="Edit album :)">
</form>

MusicApp/app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

MusicApp/app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

MusicApp/app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

MusicApp/app/views/bands/edit.html.erb
<h1>Bands#edit</h1>
<p>Find me in app/views/bands/edit.html.erb</p>

MusicApp/app/views/bands/index.html.erb
<h1>All the bands!</h1>

<% @bands.try(:each) do |band| %>
  <%= link_to "#{band.name}", band_url(band) %>
  <br><br>
<% end %>

<%= link_to "New Band", new_band_url %>

MusicApp/app/views/bands/new.html.erb
<h1>create your band</h1>

<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <input type="text" name="band[name]">
  <input type="submit" value="Create Band">
</form>

MusicApp/app/views/bands/show.html.erb
<h1><%= link_to "#{@band.name}", "/bands/" %></h1>

<% @band.albums.try(:each) do |album| %>
  <h3><%= link_to "#{album.name}", "/bands/#{@band.id}/albums/#{album.id}" %></h3>
<% end %>

<%= link_to "Add Album", "/bands/#{@band.id}/albums/new" %>

MusicApp/app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <form action="<%= sessions_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>
    <% end %>

    <%= render 'sessions/errors' %>


    <%= yield %>
  </body>
</html>

MusicApp/app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

MusicApp/app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

MusicApp/app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

MusicApp/app/views/tracks/new.html.erb
<h1>Tracks#new</h1>
<p>Find me in app/views/tracks/new.html.erb</p>

MusicApp/app/views/tracks/show.html.erb
<h1> <%= @track.name %></h1>

<h2> <%= link_to "#{@album.name}", "/bands/#{@album.band_id}/albums/#{@album.id}" %></h2>

<h2><a href="<%= @track.youtube %>">Play Dat Shiz</a></h2>

<h3> <%= @track.lyrics %></h3>

MusicApp/app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>

MusicApp/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

MusicApp/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

MusicApp/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

MusicApp/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<form action=" <%= users_url %>" method="post">
  <%= auth_token %>

  <%= email_password %>

  <input type="submit" value="Sign Up!">
</form>

MusicApp/app/views/users/show.html.erb
<h1>Welcome!</h1>
<p><%= @user.email %></p>